### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Sparkpin** [Sparkpin/CHIPy-8#1]
**REQUISITE:**
* [ ] Implement all opcodes, with exception of Syscalls and SuperChip instructions
* [ ] Add graphical display (probably PyGame)
* [ ] Add input

**OPTIONAL:**
* [ ] Memory viewer/editor
